sub EVENT_SAY {

my $say_serve = quest::saylink("serve", 1);
my $say_bind = quest::saylink("bind", 1);
my $say_simple = quest::saylink("simple", 1);
my $say_difficult = quest::saylink("difficult", 1);

if($text=~/hail/i)
{
	my $phrase = "";
	my $connect = plugin::LoadMysql();
	my $sql_query = "SHOW TABLES LIKE 'bot%'";
	my $sql_handler = $connect->prepare($sql_query);
	$sql_handler->execute();
	while (@item_row = $sql_handler->fetchrow_array())
	{
		$phrase = "If you need travel companions for your journey, look into using the '#bot help' or '#bot help create' commands to organize some henchman.";
	}

	quest::say("Greetings, $name. Have you come to $say_serve the Velvet Order? Maybe you wish for me to $say_bind you here? If it is knowledge of the many worlds you seek, perhaps you could speak to Sister Gretak in the Plane of Knowledge. If you need some rare crafting items, maybe someone from the Amethyst Blade can help. You could probably find them in the Bazaar along with many other merchants selling very valuable items. The cities often have sages or artisans that can help you find crafting items or spell scrolls, along with arcanum merchants selling rare equipment. $phrase");
}

if($text=~/bind/i){
	quest::say("Binding your soul. You will return here when you die.");
	quest::selfcast(2049);
}

if($text=~/serve/i){
quest::say("Well then, would you like to do a $say_simple task or maybe a more $say_difficult one for us?");
}

if($text=~/simple/i){
quest::taskselector(7000, 7001, 7002, 7003, 7004, 7005, 7006, 7007, 7008, 7009, 7010, 7011, 7012, 7013, 7014, 7015, 7016, 7017, 7018, 7019, 7020, 7021, 7022, 7023, 7024, 7031, 7034, 7035, 7037, 7038, 7039);
}

if($text=~/difficult/i){
quest::taskselector(7040, 7041, 7042, 7043, 7044, 7045, 7046, 7047, 7048, 7049, 7050, 7051, 7052, 7053, 7054, 7055, 7056, 7057, 7058, 7059, 7060, 7061, 7062, 7063, 7064, 7065, 7066, 7067, 7068, 7069, 7070);
}

}

sub EVENT_ITEM {
if ($itemcount{7790} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(25143);} #83
elsif ($itemcount{25143} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(25278);} #83
elsif ($itemcount{25278} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(38238);} #83
elsif ($itemcount{38238} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(38239);} #83
elsif ($itemcount{38239} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(38240);} #83
elsif ($itemcount{38240} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(38243);} #83
elsif ($itemcount{38243} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(55538);} #83
elsif ($itemcount{55538} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(7790);} #83
elsif ($itemcount{1279} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(1318);} #83
elsif ($itemcount{1318} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3351);} #83
elsif ($itemcount{3351} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3359);} #83
elsif ($itemcount{3359} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3689);} #83
elsif ($itemcount{3689} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3702);} #83
elsif ($itemcount{3702} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3715);} #83
elsif ($itemcount{3715} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(5309);} #83
elsif ($itemcount{5309} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(1279);} #83
elsif ($itemcount{7815} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(28574);} #83
elsif ($itemcount{28574} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(61016);} #83
elsif ($itemcount{61016} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(85544);} #83
elsif ($itemcount{85544} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(85598);} #83
elsif ($itemcount{85598} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(85599);} #83
elsif ($itemcount{85599} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(89019);} #83
elsif ($itemcount{89019} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(89040);} #83
elsif ($itemcount{89040} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(7815);} #83
elsif ($itemcount{1063} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(2689);} #83
elsif ($itemcount{2689} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(6955);} #83
elsif ($itemcount{6955} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(23500);} #83
elsif ($itemcount{23500} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(29820);} #83
elsif ($itemcount{29820} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(31858);} #83
elsif ($itemcount{31858} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(38260);} #83
elsif ($itemcount{38260} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(89030);} #83
elsif ($itemcount{89030} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(1063);} #83
elsif ($itemcount{2303} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(5416);} #83
elsif ($itemcount{5416} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(7232);} #83
elsif ($itemcount{7232} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(7235);} #83
elsif ($itemcount{7235} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(10574);} #83
elsif ($itemcount{10574} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(10588);} #83
elsif ($itemcount{10588} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(12209);} #83
elsif ($itemcount{12209} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(67242);} #83
elsif ($itemcount{67242} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(2303);} #83
elsif ($itemcount{11687} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(29390);} #83
elsif ($itemcount{29390} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(29396);} #83
elsif ($itemcount{29396} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(38191);} #83
elsif ($itemcount{38191} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(38196);} #83
elsif ($itemcount{38196} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(38203);} #83
elsif ($itemcount{38203} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(38205);} #83
elsif ($itemcount{38205} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(38206);} #83
elsif ($itemcount{38206} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(11687);} #83
elsif ($itemcount{4273} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(11495);} #83
elsif ($itemcount{11495} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(25650);} #83
elsif ($itemcount{25650} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(27008);} #83
elsif ($itemcount{27008} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(29246);} #83
elsif ($itemcount{29246} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(30112);} #83
elsif ($itemcount{30112} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(30261);} #83
elsif ($itemcount{30261} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(4273);} #83
elsif ($itemcount{3352} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(5676);} #83
elsif ($itemcount{5676} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(14730);} #83
elsif ($itemcount{14730} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(71519);} #83
elsif ($itemcount{71519} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(71520);} #83
elsif ($itemcount{71520} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(83990);} #83
elsif ($itemcount{83990} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(90031);} #83
elsif ($itemcount{90031} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3352);} #83
elsif ($itemcount{1900} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3357);} #83
elsif ($itemcount{3357} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3365);} #83
elsif ($itemcount{3365} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(25575);} #83
elsif ($itemcount{25575} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(31607);} #83
elsif ($itemcount{31607} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(31613);} #83
elsif ($itemcount{31613} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(31625);} #83
elsif ($itemcount{31625} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(31637);} #83
elsif ($itemcount{31637} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(1900);} #83
elsif ($itemcount{1465} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3800);} #83
elsif ($itemcount{3800} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(30029);} #83
elsif ($itemcount{30029} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(89042);} #83
elsif ($itemcount{89042} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(89043);} #83
elsif ($itemcount{89043} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(89044);} #83
elsif ($itemcount{89044} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(89059);} #83
elsif ($itemcount{89059} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(1465);} #83
elsif ($itemcount{1315} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(6979);} #83
elsif ($itemcount{6979} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(21556);} #83
elsif ($itemcount{21556} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(21557);} #83
elsif ($itemcount{21557} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(21579);} #83
elsif ($itemcount{21579} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(29637);} #83
elsif ($itemcount{29637} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(67218);} #83
elsif ($itemcount{67218} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(71310);} #83
elsif ($itemcount{71310} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(1315);} #83
elsif ($itemcount{6083} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(6084);} #83
elsif ($itemcount{6084} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(6086);} #83
elsif ($itemcount{6086} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(6088);} #83
elsif ($itemcount{6088} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(6090);} #83
elsif ($itemcount{6090} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(24014);} #83
elsif ($itemcount{24014} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(32145);} #83
elsif ($itemcount{32145} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(32146);} #83
elsif ($itemcount{32146} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(6083);} #83
elsif ($itemcount{2713} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3769);} #83
elsif ($itemcount{3769} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3772);} #83
elsif ($itemcount{3772} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(7048);} #83
elsif ($itemcount{7048} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(11153);} #83
elsif ($itemcount{11153} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(11918);} #83
elsif ($itemcount{11918} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(20440);} #83
elsif ($itemcount{20440} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(2713);} #83
elsif ($itemcount{1273} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(29251);} #83
elsif ($itemcount{29251} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(29253);} #83
elsif ($itemcount{29253} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(29254);} #83
elsif ($itemcount{29254} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(29255);} #83
elsif ($itemcount{29255} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(29259);} #83
elsif ($itemcount{29259} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(29260);} #83
elsif ($itemcount{29260} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(29265);} #83
elsif ($itemcount{29265} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(1273);} #83
elsif ($itemcount{2637} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3040);} #83
elsif ($itemcount{3040} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3042);} #83
elsif ($itemcount{3042} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3046);} #83
elsif ($itemcount{3046} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3051);} #83
elsif ($itemcount{3051} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(7390);} #83
elsif ($itemcount{7390} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(28251);} #83
elsif ($itemcount{28251} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(29728);} #83
elsif ($itemcount{29728} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(2637);} #83
elsif ($itemcount{2563} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(2565);} #83
elsif ($itemcount{2565} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(2567);} #83
elsif ($itemcount{2567} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(7586);} #83
elsif ($itemcount{7586} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(7588);} #83
elsif ($itemcount{7588} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(28263);} #83
elsif ($itemcount{28263} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(28392);} #83
elsif ($itemcount{28392} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(35096);} #83
elsif ($itemcount{35096} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(2563);} #83
elsif ($itemcount{1274} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(1727);} #83
elsif ($itemcount{1727} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3849);} #83
elsif ($itemcount{3849} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(8384);} #83
elsif ($itemcount{8384} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(13337);} #83
elsif ($itemcount{13337} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(20803);} #83
elsif ($itemcount{20803} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(27727);} #83
elsif ($itemcount{27727} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(1274);} #83
elsif ($itemcount{1978} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(2702);} #83
elsif ($itemcount{2702} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3297);} #83
elsif ($itemcount{3297} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3299);} #83
elsif ($itemcount{3299} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(7766);} #83
elsif ($itemcount{7766} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(12873);} #83
elsif ($itemcount{12873} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(29896);} #83
elsif ($itemcount{29896} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(89026);} #83
elsif ($itemcount{89026} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(1978);} #83
elsif ($itemcount{2911} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(6487);} #83
elsif ($itemcount{6487} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(6489);} #83
elsif ($itemcount{6489} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(6490);} #83
elsif ($itemcount{6490} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(20823);} #83
elsif ($itemcount{20823} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(69273);} #83
elsif ($itemcount{69273} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(89050);} #83
elsif ($itemcount{89050} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(2911);} #83
elsif ($itemcount{58835} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(58893);} #83
elsif ($itemcount{58893} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(63322);} #83
elsif ($itemcount{63322} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(63336);} #83
elsif ($itemcount{63336} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(63394);} #83
elsif ($itemcount{63394} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(63569);} #83
elsif ($itemcount{63569} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(63627);} #83
elsif ($itemcount{63627} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(58835);} #83
elsif ($itemcount{6694} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(10848);} #83
elsif ($itemcount{10848} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(11250);} #83
elsif ($itemcount{11250} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(11251);} #83
elsif ($itemcount{11251} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(11315);} #83
elsif ($itemcount{11315} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(11327);} #83
elsif ($itemcount{11327} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(11328);} #83
elsif ($itemcount{11328} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(6694);} #83
elsif ($itemcount{2711} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3533);} #83
elsif ($itemcount{3533} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3795);} #83
elsif ($itemcount{3795} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(6779);} #83
elsif ($itemcount{6779} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(8285);} #83
elsif ($itemcount{8285} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(26489);} #83
elsif ($itemcount{26489} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(26491);} #83
elsif ($itemcount{26491} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(2711);} #83
elsif ($itemcount{7173} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(7177);} #83
elsif ($itemcount{7177} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(7448);} #83
elsif ($itemcount{7448} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(7784);} #83
elsif ($itemcount{7784} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(7788);} #83
elsif ($itemcount{7788} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(7791);} #83
elsif ($itemcount{7791} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(7793);} #83
elsif ($itemcount{7793} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(7173);} #83
elsif ($itemcount{3534} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(30274);} #83
elsif ($itemcount{30274} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(52004);} #83
elsif ($itemcount{52004} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(58803);} #83
elsif ($itemcount{58803} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(63206);} #83
elsif ($itemcount{63206} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(63535);} #83
elsif ($itemcount{63535} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(63536);} #83
elsif ($itemcount{63536} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3534);} #83
elsif ($itemcount{58800} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(58858);} #83
elsif ($itemcount{58858} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(63203);} #83
elsif ($itemcount{63203} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(63359);} #83
elsif ($itemcount{63359} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(63532);} #83
elsif ($itemcount{63532} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(63534);} #83
elsif ($itemcount{63534} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(63590);} #83
elsif ($itemcount{63590} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(58800);} #83
elsif ($itemcount{2935} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3578);} #83
elsif ($itemcount{3578} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(5820);} #83
elsif ($itemcount{5820} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(7185);} #83
elsif ($itemcount{7185} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(58853);} #83
elsif ($itemcount{58853} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(63354);} #83
elsif ($itemcount{63354} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(63586);} #83
elsif ($itemcount{63586} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(2935);} #83
elsif ($itemcount{1632} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(2715);} #83
elsif ($itemcount{2715} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(2969);} #83
elsif ($itemcount{2969} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(6717);} #83
elsif ($itemcount{6717} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(30000);} #83
elsif ($itemcount{30000} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(89088);} #83
elsif ($itemcount{89088} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(90039);} #83
elsif ($itemcount{90039} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(1632);} #83
elsif ($itemcount{3884} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(6366);} #83
elsif ($itemcount{6366} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(6367);} #83
elsif ($itemcount{6367} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(10888);} #83
elsif ($itemcount{10888} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(27006);} #83
elsif ($itemcount{27006} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(36175);} #83
elsif ($itemcount{36175} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(90297);} #83
elsif ($itemcount{90297} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3884);} #83
elsif ($itemcount{3699} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3712);} #83
elsif ($itemcount{3712} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(21555);} #83
elsif ($itemcount{21555} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(21569);} #83
elsif ($itemcount{21569} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(21572);} #83
elsif ($itemcount{21572} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(24019);} #83
elsif ($itemcount{24019} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(86812);} #83
elsif ($itemcount{86812} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3699);} #83
elsif ($itemcount{3303} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3521);} #83
elsif ($itemcount{3521} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3753);} #83
elsif ($itemcount{3753} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3757);} #83
elsif ($itemcount{3757} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3760);} #83
elsif ($itemcount{3760} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(7388);} #83
elsif ($itemcount{7388} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(27012);} #83
elsif ($itemcount{27012} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3303);} #83
elsif ($itemcount{3910} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3928);} #83
elsif ($itemcount{3928} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3930);} #83
elsif ($itemcount{3930} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(5785);} #83
elsif ($itemcount{5785} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(7449);} #83
elsif ($itemcount{7449} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(8804);} #83
elsif ($itemcount{8804} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(27031);} #83
elsif ($itemcount{27031} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3910);} #83
elsif ($itemcount{24814} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(24816);} #83
elsif ($itemcount{24816} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(24818);} #83
elsif ($itemcount{24818} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(24819);} #83
elsif ($itemcount{24819} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(24820);} #83
elsif ($itemcount{24820} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(24821);} #83
elsif ($itemcount{24821} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(24823);} #83
elsif ($itemcount{24823} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(24814);} #83
elsif ($itemcount{1200} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3050);} #83
elsif ($itemcount{3050} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3603);} #83
elsif ($itemcount{3603} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3605);} #83
elsif ($itemcount{3605} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3980);} #83
elsif ($itemcount{3980} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(5161);} #83
elsif ($itemcount{5161} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(28259);} #83
elsif ($itemcount{28259} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(1200);} #83
elsif ($itemcount{8803} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(9277);} #83
elsif ($itemcount{9277} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(25069);} #83
elsif ($itemcount{25069} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(38046);} #83
elsif ($itemcount{38046} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(38060);} #83
elsif ($itemcount{38060} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(38061);} #83
elsif ($itemcount{38061} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(65149);} #83
elsif ($itemcount{65149} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(8803);} #83
elsif ($itemcount{3173} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(5373);} #83
elsif ($itemcount{5373} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(5381);} #83
elsif ($itemcount{5381} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(11692);} #83
elsif ($itemcount{11692} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(27704);} #83
elsif ($itemcount{27704} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(89068);} #83
elsif ($itemcount{89068} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(89093);} #83
elsif ($itemcount{89093} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3173);} #83
elsif ($itemcount{12556} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(29050);} #83
elsif ($itemcount{29050} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(29391);} #83
elsif ($itemcount{29391} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(30018);} #83
elsif ($itemcount{30018} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(71186);} #83
elsif ($itemcount{71186} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(89066);} #83
elsif ($itemcount{89066} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(89112);} #83
elsif ($itemcount{89112} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(12556);} #83
elsif ($itemcount{3966} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3967);} #83
elsif ($itemcount{3967} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3971);} #83
elsif ($itemcount{3971} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(11674);} #83
elsif ($itemcount{11674} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(89098);} #83
elsif ($itemcount{89098} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(89195);} #83
elsif ($itemcount{89195} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(89196);} #83
elsif ($itemcount{89196} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3966);} #83
elsif ($itemcount{3743} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(6609);} #83
elsif ($itemcount{6609} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(6836);} #83
elsif ($itemcount{6836} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(27025);} #83
elsif ($itemcount{27025} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(38038);} #83
elsif ($itemcount{38038} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(86803);} #83
elsif ($itemcount{86803} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(86804);} #83
elsif ($itemcount{86804} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3743);} #83
elsif ($itemcount{5639} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(9784);} #83
elsif ($itemcount{9784} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(27014);} #83
elsif ($itemcount{27014} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(27023);} #83
elsif ($itemcount{27023} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(27034);} #83
elsif ($itemcount{27034} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(32170);} #83
elsif ($itemcount{32170} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(63052);} #83
elsif ($itemcount{63052} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(5639);} #83
elsif ($itemcount{3522} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(5817);} #83
elsif ($itemcount{5817} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(6996);} #83
elsif ($itemcount{6996} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(7254);} #83
elsif ($itemcount{7254} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(10344);} #83
elsif ($itemcount{10344} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(27017);} #83
elsif ($itemcount{27017} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(69270);} #83
elsif ($itemcount{69270} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3522);} #83
elsif ($itemcount{3589} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(5641);} #83
elsif ($itemcount{5641} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(28400);} #83
elsif ($itemcount{28400} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(48043);} #83
elsif ($itemcount{48043} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(86865);} #83
elsif ($itemcount{86865} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(89116);} #83
elsif ($itemcount{89116} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(89118);} #83
elsif ($itemcount{89118} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3589);} #83
elsif ($itemcount{2937} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(2945);} #83
elsif ($itemcount{2945} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(2952);} #83
elsif ($itemcount{2952} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(6441);} #83
elsif ($itemcount{6441} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(8810);} #83
elsif ($itemcount{8810} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(25089);} #83
elsif ($itemcount{25089} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(38180);} #83
elsif ($itemcount{38180} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(2937);} #83
elsif ($itemcount{2714} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3427);} #83
elsif ($itemcount{3427} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3765);} #83
elsif ($itemcount{3765} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3771);} #83
elsif ($itemcount{3771} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(13618);} #83
elsif ($itemcount{13618} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(20846);} #83
elsif ($itemcount{20846} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(62648);} #83
elsif ($itemcount{62648} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(2714);} #83
elsif ($itemcount{2968} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3709);} #83
elsif ($itemcount{3709} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(6601);} #83
elsif ($itemcount{6601} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(7973);} #83
elsif ($itemcount{7973} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(20542);} #83
elsif ($itemcount{20542} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(24704);} #83
elsif ($itemcount{24704} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(65216);} #83
elsif ($itemcount{65216} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(2968);} #83
elsif ($itemcount{2712} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3531);} #83
elsif ($itemcount{3531} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(8811);} #83
elsif ($itemcount{8811} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(20811);} #83
elsif ($itemcount{20811} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(62326);} #83
elsif ($itemcount{62326} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(89146);} #83
elsif ($itemcount{89146} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(89227);} #83
elsif ($itemcount{89227} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(2712);} #83
elsif ($itemcount{3777} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3783);} #83
elsif ($itemcount{3783} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3784);} #83
elsif ($itemcount{3784} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3790);} #83
elsif ($itemcount{3790} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(65151);} #83
elsif ($itemcount{65151} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(65173);} #83
elsif ($itemcount{65173} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(65241);} #83
elsif ($itemcount{65241} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3777);} #83
elsif ($itemcount{2954} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3738);} #83
elsif ($itemcount{3738} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3742);} #83
elsif ($itemcount{3742} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(10895);} #83
elsif ($itemcount{10895} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(65176);} #83
elsif ($itemcount{65176} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(65220);} #83
elsif ($itemcount{65220} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(65242);} #83
elsif ($itemcount{65242} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(2954);} #83
elsif ($itemcount{7873} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(14732);} #83
elsif ($itemcount{14732} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(16815);} #83
elsif ($itemcount{16815} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(27261);} #83
elsif ($itemcount{27261} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(62322);} #83
elsif ($itemcount{62322} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(63644);} #83
elsif ($itemcount{63644} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(89162);} #83
elsif ($itemcount{89162} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(7873);} #83
elsif ($itemcount{1705} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3043);} #83
elsif ($itemcount{3043} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3752);} #83
elsif ($itemcount{3752} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(5368);} #83
elsif ($itemcount{5368} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(11620);} #83
elsif ($itemcount{11620} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(77504);} #83
elsif ($itemcount{77504} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(89231);} #83
elsif ($itemcount{89231} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(1705);} #83
elsif ($itemcount{3963} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(6262);} #83
elsif ($itemcount{6262} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(8036);} #83
elsif ($itemcount{8036} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(10911);} #83
elsif ($itemcount{10911} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(89097);} #83
elsif ($itemcount{89097} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(89105);} #83
elsif ($itemcount{89105} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(89142);} #83
elsif ($itemcount{89142} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3963);} #83
elsif ($itemcount{6257} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(8843);} #83
elsif ($itemcount{8843} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(9823);} #83
elsif ($itemcount{9823} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(9832);} #83
elsif ($itemcount{9832} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(89063);} #83
elsif ($itemcount{89063} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(89129);} #83
elsif ($itemcount{89129} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(89265);} #83
elsif ($itemcount{89265} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(6257);} #83
elsif ($itemcount{3959} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3962);} #83
elsif ($itemcount{3962} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(28403);} #83
elsif ($itemcount{28403} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(63668);} #83
elsif ($itemcount{63668} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(69276);} #83
elsif ($itemcount{69276} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(86873);} #83
elsif ($itemcount{86873} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(89121);} #83
elsif ($itemcount{89121} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(3959);} #83
elsif ($itemcount{11273} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(13569);} #83
elsif ($itemcount{13569} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(28324);} #83
elsif ($itemcount{28324} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(28345);} #83
elsif ($itemcount{28345} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(11273);} #83
elsif ($itemcount{24722} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(54039);} #83
elsif ($itemcount{54039} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(61021);} #83
elsif ($itemcount{61021} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(89111);} #83
elsif ($itemcount{89111} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(89127);} #83
elsif ($itemcount{89127} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(24722);} #83
elsif ($itemcount{5221} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(12530);} #83
elsif ($itemcount{12530} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(28339);} #83
elsif ($itemcount{28339} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(28340);} #83
elsif ($itemcount{28340} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(29696);} #83
elsif ($itemcount{29696} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(86672);} #83
elsif ($itemcount{86672} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(89010);} #83
elsif ($itemcount{89010} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(5221);} #83
elsif ($itemcount{6169} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(7962);} #83
elsif ($itemcount{7962} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(9242);} #83
elsif ($itemcount{9242} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(11027);} #83
elsif ($itemcount{11027} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(21926);} #83
elsif ($itemcount{21926} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(58912);} #83
elsif ($itemcount{58912} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(89089);} #83
elsif ($itemcount{89089} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(6169);} #83
elsif ($itemcount{11180} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(12666);} #83
elsif ($itemcount{12666} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(27070);} #83
elsif ($itemcount{27070} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(28326);} #83
elsif ($itemcount{28326} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(75665);} #83
elsif ($itemcount{75665} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(75677);} #83
elsif ($itemcount{75677} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(11180);} #83
elsif ($itemcount{22962} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(24519);} #83
elsif ($itemcount{24519} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(27048);} #83
elsif ($itemcount{27048} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(27050);} #83
elsif ($itemcount{27050} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(27058);} #83
elsif ($itemcount{27058} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(29554);} #83
elsif ($itemcount{29554} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(22962);} #83
elsif ($itemcount{31468} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(61022);} #83
elsif ($itemcount{61022} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(31468);} #83
elsif ($itemcount{8119} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(9428);} #83
elsif ($itemcount{9428} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(27039);} #83
elsif ($itemcount{27039} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(27055);} #83
elsif ($itemcount{27055} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(27085);} #83
elsif ($itemcount{27085} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(85571);} #83
elsif ($itemcount{85571} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(8119);} #83
elsif ($itemcount{8747} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(15637);} #83
elsif ($itemcount{15637} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(21924);} #83
elsif ($itemcount{21924} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(27716);} #83
elsif ($itemcount{27716} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(31394);} #83
elsif ($itemcount{31394} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(69286);} #83
elsif ($itemcount{69286} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(89135);} #83
elsif ($itemcount{89135} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(8747);} #83
elsif ($itemcount{6825} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(8749);} #83
elsif ($itemcount{8749} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(11000);} #83
elsif ($itemcount{11000} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(31460);} #83
elsif ($itemcount{31460} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(31461);} #83
elsif ($itemcount{31461} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(31467);} #83
elsif ($itemcount{31467} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(89236);} #83
elsif ($itemcount{89236} == 1 ){quest::say("This item does not please you? How about this one?"); quest::summonitem(6825);} #83
}